version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: booking-api-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - booking-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-api-app
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
      API_PREFIX: ${API_PREFIX}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    networks:
      - booking-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  booking-network:
    driver: bridge
